name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test action
    steps:
      - uses: actions/checkout@v4

      - uses: vietanhduong/auto-approve-action@feat/init
        with:
          github-token: ${{ secrets.GH_PAT }}
          pr-number: "1"
          comment-body: |
            # Auto Approved
            ## This PR has been approved by the auto-approve-action
