name: Test

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4

      - id: foo
        uses: vietanhduong/auto-approve-action@feat/init
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
