name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test action
    steps:
      - uses: actions/checkout@v4

      - uses: vietanhduong/auto-approve-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
